name: Messenger Bot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Force Fix package.json
      run: |
        # package.json এর ভেতরের ভুল ভার্সন আর ফাঁকা ভার্সন স্ক্রিপ্ট দিয়ে অটো ঠিক করা হচ্ছে
        sed -i 's/"nayan-apis-server": "^2.4.6"/"nayan-apis-server": "latest"/g' package.json
        sed -i 's/"string-similarity": ""/"string-similarity": "latest"/g' package.json

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Start Messenger Bot
      run: npm run start
