name: Messenger Bot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Bypass and Force Install Bot
      run: |
        # ত্রুটিযুক্ত package.json ফাইল পুরোপুরি এড়িয়ে ফ্রেশভাবে প্রজেক্ট সেটআপ করা হচ্ছে
        rm -f package-lock.json
        npm init -y
        npm install express axios dotenv fs-extra chalk request @googlethis/googlethis fluent-ffmpeg qrcode-reader jimp ytdl-core --legacy-peer-deps
        npm install nayan-apis-server@latest --legacy-peer-deps
        npm install string-similarity --legacy-peer-deps

    - name: Start Messenger Bot
      run: npm run start || node Nayan/catalogs/Nayana.js
